### ISSUE TITLE
Crash on Kalico

### ISSUE THREAD

**Issue by ksummers92** [MRX8024/motors-sync#44]
**Describe the bug**
Updated motors-sync and Klipper failed to load due to lack of motion_queuing in Kalico. I rollback to commit 7c17bf0841dd00705f6dd39bcd5dfb4ed9c8db8f and now I am getting a shutdown when trying to run sync_motors. Below is the error from the log (log attached):
`Internal Error on WebRequest: gcode/script
Traceback (most recent call last):
  File "/home/trident/klipper/klippy/webhooks.py", line 300, in _process_request
    func(web_request)
  File "/home/trident/klipper/klippy/webhooks.py", line 518, in _handle_script
    self.gcode.run_script(web_request.get_str("script"))
  File "/home/trident/klipper/klippy/gcode.py", line 340, in run_script
    self._process_commands(script.split("\n"), need_ack=False)
  File "/home/trident/klipper/klippy/gcode.py", line 313, in _process_commands
    handler(gcmd)
  File "/home/trident/klipper/klippy/gcode.py", line 222, in func
    return origfunc(self._get_extended_params(params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trident/klipper/klippy/extras/gcode_macro.py", line 490, in cmd
    self.template.run_gcode_from_command(kwparams)
  File "/home/trident/klipper/klippy/extras/gcode_macro.py", line 129, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
  File "/home/trident/klipper/klippy/gcode.py", line 331, in run_script_from_command
    self._process_commands(script.split("\n"), need_ack=False)
  File "/home/trident/klipper/klippy/gcode.py", line 313, in _process_commands
    handler(gcmd)
  File "/home/trident/klipper/klippy/gcode.py", line 222, in func
    return origfunc(self._get_extended_params(params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trident/klipper/klippy/extras/motors_sync.py", line 1064, in cmd_SYNC_MOTORS
    raise self.gcode.error('Error in sync methods!')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trident/klipper/klippy/extras/motors_sync.py", line 920, in handle_state
    last_abs_pos = abs_pos
  File "/home/trident/klipper/klippy/extras/motors_sync.py", line 75, in start_measurements
    self.aclient.request_start_time = self.toolhead.get_last_move_time()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BeaconProbe' object has no attribute 'batch_bulk'
MCU 'beacon' shutdown: Emergency stop
`

**Expected behavior**
I expected that once I rolled back to previous commit that the plugin would behave the same as before.

**Logs**
[klippy (81).log](https://github.com/user-attachments/files/23568960/klippy.81.log)

**Comment by MRX8024** [comment]
After a rollback, you need to completely restart the klipper service, e.g. `sudo systemctl restart klipper`.

Thanks for the report, the issue only affects beacon and was broken in 51a3c04, I'll try to fix it in the next few days.

**Comment by MRX8024** [comment]
However, regarding the lack of `motion_queuing` in Kalico, my script may stop supporting that project at this point. I primarily write code for Klipper mainline, and I have no desire to support any other third-party projects whose authors can't adhere to Klipper mainline. I don't really want to add hacks to the code to support two different projects, and separating into different branches will add double the work of merging them.

This generally applies to beacon as well, as its authors didn't write their software using the same concepts as Klipper, but at least this problem can be solved easily and in a one-time solution.

I might just find a way to make this work for Kalico for now, but in the future such exceptions might occur more often and I won't try to fix them.

This is the reason why I won't roll back main to a working commit, because for Klipper mainline all works.

I am writing this message because it is likely that a certain number of people will look at this issue, and to give them an understanding of the current realities of Kalico.

**Comment by ttpimpin** [comment]
hey, i was now about to post on this. thanks for the updates and responses. i'll rollback for now also

**Comment by MRX8024** [comment]
I added two commits to the dev branch with fixes for both Beacon and Kalico. I don't know if this works, so it would be nice if someone could check it. Please attach the klippy.log, regardless of whether these changes worked.

**Comment by WojciechBednarski** [comment]
> I added two commits to the dev branch with fixes for both Beacon and Kalico. I don't know if this works, so it would be nice if someone could check it. Please attach the klippy.log, regardless of whether these changes worked.

You're the best. It works fine on kalico bleeding edge. I tried all the commands just to be sure. 
[klippy (10).log](https://github.com/user-attachments/files/23594550/klippy.10.log)

**Comment by MRX8024** [comment]
Okay, thanks, I've merged one commit in main for Kalico support. But for the second one with the Beacon changes I'll still be waiting for tests from other users.

**Comment by ttpimpin** [comment]
> I added two commits to the dev branch with fixes for both Beacon and Kalico. I don't know if this works, so it would be nice if someone could check it. Please attach the klippy.log, regardless of whether these changes worked.

it works great, thank you for this and for your great work

**Comment by MRX8024** [comment]
> it works great, thank you for this and for your great work

Since this issue covers two issues in two different commits, It's a little unclear which issue you're talking about, Beacon or Kalico support?

**Comment by ttpimpin** [comment]
> > it works great, thank you for this and for your great work
> 
> Since this issue covers two issues in two different commits, It's a little unclear which issue you're talking about, Beacon or Kalico support?

ooh lmao i forgot about the beacon issue.. i'm running kalico and it works for that. i'm on dev branch, but i can move to main to test your changes

**Comment by MRX8024** [comment]
Well, main contains the same changes, so there's no reason for it not to work. You can probably switch back to main, though, since this is a development branch, and I often release raw code and then test it, sometimes doing force pushes, etc.

**Comment by ttpimpin** [comment]
back on main, all works good

**Comment by ksummers92** [comment]
Hello @MRX8024, Beacon still seems to be incompatible with motors-sync. After updating to latest, I am getting the following error (klippy log attached as well)

[klippy.log](https://github.com/user-attachments/files/23727312/klippy.log)

:
`Internal error on command:"_MODULE_CUSTOM4"
Traceback (most recent call last):
  File "/home/trident/klipper/klippy/gcode.py", line 313, in _process_commands
    handler(gcmd)
  File "/home/trident/klipper/klippy/gcode.py", line 222, in func
    return origfunc(self._get_extended_params(params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trident/klipper/klippy/extras/gcode_macro.py", line 490, in cmd
    self.template.run_gcode_from_command(kwparams)
  File "/home/trident/klipper/klippy/extras/gcode_macro.py", line 129, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
  File "/home/trident/klipper/klippy/gcode.py", line 331, in run_script_from_command
    self._process_commands(script.split("\n"), need_ack=False)
  File "/home/trident/klipper/klippy/gcode.py", line 313, in _process_commands
    handler(gcmd)
  File "/home/trident/klipper/klippy/gcode.py", line 222, in func
    return origfunc(self._get_extended_params(params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trident/klipper/klippy/extras/gcode_macro.py", line 490, in cmd
    self.template.run_gcode_from_command(kwparams)
  File "/home/trident/klipper/klippy/extras/gcode_macro.py", line 129, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
  File "/home/trident/klipper/klippy/gcode.py", line 331, in run_script_from_command
    self._process_commands(script.split("\n"), need_ack=False)
  File "/home/trident/klipper/klippy/gcode.py", line 313, in _process_commands
    handler(gcmd)
  File "/home/trident/klipper/klippy/gcode.py", line 222, in func
    return origfunc(self._get_extended_params(params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trident/klipper/klippy/extras/motors_sync.py", line 1143, in cmd_SYNC_MOTORS
    self.handle_state(self.motion[axis], 'start')
  File "/home/trident/klipper/klippy/extras/motors_sync.py", line 999, in handle_state
    axis.chip_helper.start_measurements()
  File "/home/trident/klipper/klippy/extras/motors_sync.py", line 157, in start_measurements
    self.chip_config.batch_bulk.add_client(self._handle_batch)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BeaconProbe' object has no attribute 'batch_bulk'
Internal error on command:"_MODULE_CUSTOM4"
Internal error on command:"START_PRINT"
Traceback (most recent call last):
  File "/home/trident/klipper/klippy/gcode.py", line 313, in _process_commands
    handler(gcmd)
  File "/home/trident/klipper/klippy/gcode.py", line 222, in func
    return origfunc(self._get_extended_params(params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trident/klipper/klippy/extras/gcode_macro.py", line 490, in cmd
    self.template.run_gcode_from_command(kwparams)
  File "/home/trident/klipper/klippy/extras/gcode_macro.py", line 129, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
  File "/home/trident/klipper/klippy/gcode.py", line 331, in run_script_from_command
    self._process_commands(script.split("\n"), need_ack=False)
  File "/home/trident/klipper/klippy/gcode.py", line 313, in _process_commands
    handler(gcmd)
  File "/home/trident/klipper/klippy/gcode.py", line 222, in func
    return origfunc(self._get_extended_params(params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trident/klipper/klippy/extras/gcode_macro.py", line 490, in cmd
    self.template.run_gcode_from_command(kwparams)
  File "/home/trident/klipper/klippy/extras/gcode_macro.py", line 129, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
  File "/home/trident/klipper/klippy/gcode.py", line 331, in run_script_from_command
    self._process_commands(script.split("\n"), need_ack=False)
  File "/home/trident/klipper/klippy/gcode.py", line 313, in _process_commands
    handler(gcmd)
  File "/home/trident/klipper/klippy/gcode.py", line 222, in func
    return origfunc(self._get_extended_params(params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trident/klipper/klippy/extras/gcode_macro.py", line 490, in cmd
    self.template.run_gcode_from_command(kwparams)
  File "/home/trident/klipper/klippy/extras/gcode_macro.py", line 129, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
  File "/home/trident/klipper/klippy/gcode.py", line 331, in run_script_from_command
    self._process_commands(script.split("\n"), need_ack=False)
  File "/home/trident/klipper/klippy/gcode.py", line 313, in _process_commands
    handler(gcmd)
  File "/home/trident/klipper/klippy/gcode.py", line 222, in func
    return origfunc(self._get_extended_params(params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trident/klipper/klippy/extras/motors_sync.py", line 1143, in cmd_SYNC_MOTORS
    self.handle_state(self.motion[axis], 'start')
  File "/home/trident/klipper/klippy/extras/motors_sync.py", line 999, in handle_state
    axis.chip_helper.start_measurements()
  File "/home/trident/klipper/klippy/extras/motors_sync.py", line 157, in start_measurements
    self.chip_config.batch_bulk.add_client(self._handle_batch)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BeaconProbe' object has no attribute 'batch_bulk'
Internal error on command:"START_PRINT"
virtual_sdcard dispatch
Traceback (most recent call last):
  File "/home/trident/klipper/klippy/extras/virtual_sdcard.py", line 322, in work_handler
    self.gcode.run_script(line)
  File "/home/trident/klipper/klippy/gcode.py", line 340, in run_script
    self._process_commands(script.split("\n"), need_ack=False)
  File "/home/trident/klipper/klippy/gcode.py", line 313, in _process_commands
    handler(gcmd)
  File "/home/trident/klipper/klippy/gcode.py", line 222, in func
    return origfunc(self._get_extended_params(params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trident/klipper/klippy/extras/gcode_macro.py", line 490, in cmd
    self.template.run_gcode_from_command(kwparams)
  File "/home/trident/klipper/klippy/extras/gcode_macro.py", line 129, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
  File "/home/trident/klipper/klippy/gcode.py", line 331, in run_script_from_command
    self._process_commands(script.split("\n"), need_ack=False)
  File "/home/trident/klipper/klippy/gcode.py", line 313, in _process_commands
    handler(gcmd)
  File "/home/trident/klipper/klippy/gcode.py", line 222, in func
    return origfunc(self._get_extended_params(params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trident/klipper/klippy/extras/gcode_macro.py", line 490, in cmd
    self.template.run_gcode_from_command(kwparams)
  File "/home/trident/klipper/klippy/extras/gcode_macro.py", line 129, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
  File "/home/trident/klipper/klippy/gcode.py", line 331, in run_script_from_command
    self._process_commands(script.split("\n"), need_ack=False)
  File "/home/trident/klipper/klippy/gcode.py", line 313, in _process_commands
    handler(gcmd)
  File "/home/trident/klipper/klippy/gcode.py", line 222, in func
    return origfunc(self._get_extended_params(params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trident/klipper/klippy/extras/gcode_macro.py", line 490, in cmd
    self.template.run_gcode_from_command(kwparams)
  File "/home/trident/klipper/klippy/extras/gcode_macro.py", line 129, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
  File "/home/trident/klipper/klippy/gcode.py", line 331, in run_script_from_command
    self._process_commands(script.split("\n"), need_ack=False)
  File "/home/trident/klipper/klippy/gcode.py", line 313, in _process_commands
    handler(gcmd)
  File "/home/trident/klipper/klippy/gcode.py", line 222, in func
    return origfunc(self._get_extended_params(params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trident/klipper/klippy/extras/motors_sync.py", line 1143, in cmd_SYNC_MOTORS
    self.handle_state(self.motion[axis], 'start')
  File "/home/trident/klipper/klippy/extras/motors_sync.py", line 999, in handle_state
    axis.chip_helper.start_measurements()
  File "/home/trident/klipper/klippy/extras/motors_sync.py", line 157, in start_measurements
    self.chip_config.batch_bulk.add_client(self._handle_batch)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BeaconProbe' object has no attribute 'batch_bulk'
Exiting SD card print (position 45299)
`

**Comment by ksummers92** [comment]
Ah, I assumed from the previous comments that the beacon patch was also committed to main. I switched to dev and it seems to work. Thanks!

**Comment by MRX8024** [comment]
Okay, I'll try to merge it into main in the next few days
