### PR TITLE
Fix reference from self.axes to new self.conf_axes

### PR DESCRIPTION
**Pull request by timwu**
Looks like current head crashes on `SYNC_MOTORS_CALIBRATE` with this error:

```
Traceback (most recent call last):
  File "/home/tim/klipper/klippy/webhooks.py", line 282, in _process_request
    func(web_request)
  File "/home/tim/klipper/klippy/webhooks.py", line 481, in _handle_script
    self.gcode.run_script(web_request.get_str("script"))
  File "/home/tim/klipper/klippy/gcode.py", line 321, in run_script
    self._process_commands(script.split("\n"), need_ack=False)
  File "/home/tim/klipper/klippy/gcode.py", line 298, in _process_commands
    handler(gcmd)
  File "/home/tim/klipper/klippy/gcode.py", line 207, in func
    return origfunc(self._get_extended_params(params))
  File "/home/tim/klipper/klippy/extras/motors_sync.py", line 465, in cmd_CALIBRATE_SYNC
    axis = gcmd.get_int('AXIS', self.axes[0])
AttributeError: 'MotorsSync' object has no attribute 'axes'
```

The breakage seems to have been caused by 456b54efbd9baecf9a082a694c87ead79133ca5e which changed the `self.axes` member to `self.conf_axes`.

### CODE REVIEW

**Comment by MRX8024** [comment]
Thank you! I missed this probably because I started the calibration after performing the synchronization manually, when `self.axes` has already been defined/

-Maxim
